# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/MEMENBOT',
                'doc_host': 'https://ruescog.github.io',
                'git_url': 'https://github.com/ruescog/MEMENBOT',
                'lib_path': 'MEMENBOT'},
  'syms': {'MEMENBOT.core': {'MEMENBOT.core.foo': ('core.html#foo', 'MEMENBOT/core.py')}}}